### NUMPY
Creación e indexación:

In [1]:
import numpy as np

In [8]:
# 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array_uni = np.random.random_sample(50)
multiplos5 = array_uni[::5]
print(f'Los múltiplos de 5 son:{multiplos5}')

Los múltiplos de 5 son:[0.49318025 0.60980574 0.54544053 0.25670153 0.61163031 0.53704793
 0.93165128 0.30329956 0.15272063 0.63912298]


In [13]:
# 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

array_uni2 = np.random.rand(1, 21, 30)
print(array_uni2)

print('Los elementos impares son:', array_uni2[1:2])

[[[0.85670811 0.85057197 0.38299237 0.76455962 0.31771325 0.33296732
   0.74813847 0.072847   0.45451403 0.62391263 0.34989739 0.65284005
   0.20452881 0.72535824 0.32605508 0.53830282 0.7472101  0.91342116
   0.40571986 0.95865799 0.84919645 0.44856963 0.13800047 0.49692664
   0.66408458 0.63050943 0.98466191 0.3329231  0.23824484 0.54263387]
  [0.90679257 0.70120791 0.08410729 0.39699494 0.09572153 0.38352001
   0.86501785 0.50888524 0.73755321 0.68620246 0.8409767  0.41805044
   0.10173521 0.54484358 0.66132521 0.39008438 0.77914682 0.67722295
   0.76681344 0.62075496 0.15937223 0.18058099 0.258795   0.31770141
   0.60259663 0.1117018  0.65073831 0.52276303 0.94062972 0.4064714 ]
  [0.81681064 0.63604653 0.32925048 0.51346623 0.10013367 0.55657235
   0.33635673 0.54247779 0.44237007 0.74982409 0.59197649 0.61828485
   0.32653456 0.3315715  0.19288796 0.33013253 0.46603692 0.30778705
   0.75290282 0.2241747  0.48533361 0.62717134 0.87040013 0.47785085
   0.5682501  0.68066986 0.93133

In [14]:
# 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

array3 = (np.random.random((4, 6)) * 90) + 10  # Escalar y desplazar para obtener el rango entre 10 y 100
array3 = np.round(array3, 2)  # Redondear los decimales a 2 decimales
print("Array 2D original:")
print(array3)

# Acceder a la última fila de la matriz
last_row = array3[-1, :]
print("\nÚltima fila de la matriz:")
print(last_row)

Array 2D original:
[[14.11 30.   31.72 80.71 60.63 48.17]
 [98.63 14.13 80.27 84.68 58.41 44.45]
 [97.53 37.54 58.93 59.08 63.85 32.83]
 [76.89 96.79 70.66 62.14 20.69 99.31]]

Última fila de la matriz:
[76.89 96.79 70.66 62.14 20.69 99.31]


In [17]:
# 4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). 
# Reemplaza los elementos en posiciones múltiplos de 3 por 0.

array4 = np.random.randint(0, 101, (2, 3, 5))

# Reemplazar los elementos en posiciones múltiplos de 3 por 0
array4_flat = array4.flatten()  # Convertir el array a 1D para facilitar el acceso
array4_flat[::3] = 0
array4 = array4_flat.reshape((2, 3, 5))  # Reconstruir el array 3D
print("\nArray 3D con elementos en posiciones múltiplos de 3 reemplazados por 0:")
print(array4)


Array 3D con elementos en posiciones múltiplos de 3 reemplazados por 0:
[[[ 0 27 95  0 79]
  [19  0 49 30  0]
  [34 80  0 61 95]]

 [[ 0 83 97  0 96]
  [15  0 45 30  0]
  [51 13  0  7 29]]]


Preguntas teóricas:
¿Qué diferencia existe entre el reshape y el transpose?
reshape:

Propósito: Cambia la forma del array sin alterar los datos subyacentes. Uso: Especificas la nueva forma que quieres para el array, siempre que el número total de elementos se mantenga constante. Ejemplo simple: Cambiar un array de 12 elementos de 1D (una dimensión) a 2D (dos dimensiones) con 3 filas y 4 columnas.

transpose:

Propósito: Permuta los ejes del array. Uso: Cambia el orden de las dimensiones del array, reorganizando cómo se disponen los elementos. Ejemplo simple: Convertir un array 2D de 3x4 (3 filas y 4 columnas) a 4x3 (4 filas y 3 columnas) intercambiando filas por columnas.

¿Y entre el transpose y el swapaxes?
transpose:

Propósito: Permuta todos los ejes del array según el orden que especifiques. Uso: Se utiliza para reordenar completamente las dimensiones del array. Ejemplo simple: Cambiar un array 3D de forma (2, 3, 4) a (4, 3, 2) especificando el nuevo orden de los ejes.

swapaxes:

Propósito: Intercambia solo dos ejes específicos del array. Uso: Especificas dos ejes para intercambiar su posición. Ejemplo simple: Cambiar un array 3D de forma (2, 3, 4) a (4, 3, 2) intercambiando solo el primer y el tercer eje.

### Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [18]:
# Crear el array 3D con valores entre 0 y 1, y redondearlos a 1 decimal
array_3d = np.round(np.random.random((2, 3, 5)), 1)
print("Array 3D original:")
print(array_3d)

Array 3D original:
[[[0.8 0.6 0.9 0.5 0.4]
  [0.2 0.1 0.2 0.7 0.2]
  [0.1 0.7 0.3 0.5 0.8]]

 [[0.3 0.7 0.7 0.8 0.6]
  [0.9 0.  0.4 0.1 0.6]
  [0.9 0.8 0.5 0.3 0. ]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [21]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]]

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]]

[[['A', 'B', 'C', 'B', 'C'],
  ['C', 'B', 'B', 'C', 'C'],
  ['D', 'C', 'C', 'B', 'C']],
 [['E', 'C', 'A', 'B', 'C'],
  ['B', 'B', 'B', 'E', 'B'],
  ['B', 'C', 'B', 'B', 'C']]]

In [22]:
# Crear un array vacío con la misma forma que array_3d
array_replacement = np.empty(array_3d.shape, dtype=str)


# Calcular la media, el máximo y el mínimo del array original
media = np.mean(array_3d)
maximo = np.max(array_3d)
minimo = np.min(array_3d)

print("la media es:",media) 
print("el maximo es:",maximo)
print("el minimo es:",minimo)


# Usar np.where para reemplazar valores según las condiciones
array_replacement = np.where(array_3d == maximo, 'D',
                    np.where(array_3d == minimo, 'E',
                    np.where(array_3d == media, 'A',
                    np.where(array_3d > media, 'B',
                    np.where(array_3d < media, 'C', '')))))



print("*-*-*-*-*-*-*-*-*-*-*-*")
print("el nuevo array es:",array_replacement)

la media es: 0.4866666666666667
el maximo es: 0.9
el minimo es: 0.0
*-*-*-*-*-*-*-*-*-*-*-*
el nuevo array es: [[['B' 'B' 'D' 'B' 'C']
  ['C' 'C' 'C' 'B' 'C']
  ['C' 'B' 'C' 'B' 'B']]

 [['C' 'B' 'B' 'B' 'B']
  ['D' 'E' 'C' 'C' 'B']
  ['D' 'B' 'B' 'C' 'E']]]
