#  Instalar NumPy
📌Antes de ponernos a trabajar con NumPy tendremos que instalar la librería, para eso lo que tendremos que hacer es escribir en la terminal la siguiente línea de código.
```bash
!pip install numpy
```

# Creación de *arrays*

NumPy permite crear *arrays* de distintas formas las más comunes son:

1. **Crear un array a partir de una lista**: Puedes crear un *array* NumPy a partir de una lista utilizando la función `np.array()`.

2. **Crear un array vacío**: Puedes crear un *array* vacío especificando la forma deseada utilizando la función `np.empty()`. Debemos tener en cuenta que los valores del array vacío pueden ser impredecibles, ya que toman los valores almacenados en la memoria en ese momento.

3. **Crear un array de ceros**: Puedes crear un *array* con todos los elementos establecidos en cero utilizando la función `np.zeros()`. 

4. **Crear un array de unos**: Puedes crear un *array* con todos los elementos establecidos en uno utilizando la función `np.ones()`.

5. **Crear un array con valores secuenciales**: Puedes crear un *array* con valores secuenciales utilizando la función `np.arange()`. 

6. **Crear un array usando random de NumPy**: Puedes crear un *array* con números aleatorios usando distintos métodos de `random` en NumPy


In [2]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

## Crear un array a partir de una lista

In [4]:
print("-------------ARRAY UNIDIMENSIONAL--------------")

# definimos una lista que usaremos para convertir en array unidimensional
lista = [1, 2, 3, 4, 5]
print("La lista a partir de la que crearemos un array unidimensional es:", lista)

# convertimos la lista en array usando el método 'np.array()' 
array_unidimensional = np.array(lista)
print(f"El array unidimensional creado a partir de la lista es: \n  {array_unidimensional} \n")

print("\n -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-\n ")

print("-------------ARRAY BIDIMENSIONAL--------------")
# para crear un array bidimensional necesitaremos una lista de listas
lista_listas = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print("La lista de listas a partir de la que crearemos un array bidimensional es:", lista_listas)

# convertimos la lista en array usando el método 'np.array()' 
# 📌 fijaos como ahora el array que hemos construido tiene "filas" y "columnas"
array_bidimensional = np.array(lista_listas)
print(f"El array bidimensional creado a partir de la lista es:\n  {array_bidimensional}\n")

print("\n -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-\n ")

print("-------------ARRAY TRIDIMENSIONAL--------------")
# para crear un array tridimensional necesitaremos una lista de listas de listas 🤯. 
lista_listas_listas = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]
print("La lista de listas de listas a partir de la que crearemos un array tridimensional es:", lista_listas_listas)

# convertimos la lista en array usando el método 'np.array()' 
# fijaos como ahora el array que hemos construido tiene "filas" y "columnas"
array_tridimensional = np.array(lista_listas_listas)
print(f"El array tridimensional creado a partir de la lista es:\n  {array_tridimensional}\n")

-------------ARRAY UNIDIMENSIONAL--------------
La lista a partir de la que crearemos un array unidimensional es: [1, 2, 3, 4, 5]
El array unidimensional creado a partir de la lista es: 
  [1 2 3 4 5] 


 -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
 
-------------ARRAY BIDIMENSIONAL--------------
La lista de listas a partir de la que crearemos un array bidimensional es: [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
El array bidimensional creado a partir de la lista es:
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


 -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
 
-------------ARRAY TRIDIMENSIONAL--------------
La lista de listas de listas a partir de la que crearemos un array tridimensional es: [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]
El array tridimensional creado a partir de la lista es:
  [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 1

Acabamos de aprender a crear *arrays* de distintas dimensiones, y como vemos en el print anterior vemos que tienen distintas formas, pero solo podemos decir eso. Exploremos ahora, con una serie de métodos específicos, cuales son las propiedades de cada uno de estos *arrays* para entender mejor sus diferencias. 

NumPy ofrece una variedad de métodos útiles para comprender y explorar las propiedades de un *array*. Veamos los más importantes:

1. **Forma del array**: El método `shape` devuelve una tupla que representa la forma (dimensiones) del *array*. Cada elemento de la tupla representa el tamaño de una dimensión. 

2. **Número de dimensiones**: El atributo `ndim` devuelve el número de dimensiones del *array*.

3. **Tamaño total del array**: El atributo `size` devuelve el número total de elementos en el *array*. 


4. **Tipo de datos del array**: El atributo `dtype` devuelve el tipo de datos de los elementos del *array*. 


In [5]:
print("-------------ARRAY UNIDIMENSIONAL--------------")
print(f"El array unidimensional es: \n  {array_unidimensional}")
print(f"La forma del array unidimensional es: {array_unidimensional.shape}")
print(f"El número de dimensiones del array unidimensional es: {array_unidimensional.ndim}")
print(f"El número de elementos del array unidimensional es: {array_unidimensional.size}")
print(f"El tipo de dato que tenemos en el array unidimensional es: {array_unidimensional.dtype}\n")

-------------ARRAY UNIDIMENSIONAL--------------
El array unidimensional es: 
  [1 2 3 4 5]
La forma del array unidimensional es: (5,)
El número de dimensiones del array unidimensional es: 1
El número de elementos del array unidimensional es: 5
El tipo de dato que tenemos en el array unidimensional es: int32



Entendamos los resultados que hemos obtenido en la celda anterior: 

- ***array* unidimensional**

    - *Forma*: el método `shape` nos devuelve una tupla donde nos va indicar el número de elementos que tenemos por cada dimensión que tiene nuestro *array*. En este caso, nos devuelve una tupla de un solo elemento porque solo tenemos una dimensión que tiene 5 elementos. 

    - *Número de dimensiones*: para entender bien que es lo que nos devuelve el atributo `ndim` necesitamos comprender que es una dimensión en el contexto de un *array*. En términos simples, una dimensión en un *array* se refiere a la cantidad de índices necesarios para acceder a un elemento dentro del *array*. Por ejemplo, un *array* unidimensional requiere un solo índice para acceder a un elemento, mientras que un *array* bidimensional requiere dos índices (uno para la fila y otro para la columna). Entendiendo esto,  y pensando que la indexación en *arrays* es como en las listas, en nuestro caso solo necesitamos un índice para acceder a algún valor dentro del *array*, por lo que la dimensión de este *array* es de 1

    - *Número de elementos*: con el atributo `size` nos dice el número de elementos que  hay dentro del *array*, en este caso tenemos 5 números enteros

    - *Tipo de datos*: usando el atributo `dtype` conocemos que  el *array* esta compuesto por elementos de tipo *integer*. Recordad que en un *array* todos los elementos deben ser del mismo tipo. 


In [6]:
print("-------------ARRAY BIDIMENSIONAL--------------")
print(f"El array bidimensional es: \n  {array_bidimensional}")
print(f"La forma del array bidimensional es: {array_bidimensional.shape}")
print(f"El número de dimensiones del array bidimensional es: {array_bidimensional.ndim}")
print(f"El número de elementos del array bidimensional es: {array_bidimensional.size}")
print(f"El tipo de dato que tenemos en el array bidimensional es: {array_bidimensional.dtype}\n")

-------------ARRAY BIDIMENSIONAL--------------
El array bidimensional es: 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
La forma del array bidimensional es: (2, 5)
El número de dimensiones del array bidimensional es: 2
El número de elementos del array bidimensional es: 10
El tipo de dato que tenemos en el array bidimensional es: int32



Entendamos los resultados que hemos obtenido en la celda anterior: 


- ***array* bidimensional**

    - *Forma*: en este caso la tupla esta compuesta por dos valores, podríamos decir que tenemos "filas" y "columnas". En concreto nos esta diciendo que tenemos 2 filas y 5 columnas. 

    - *Número de dimensiones*: En este caso necesitamos dos índices para acceder a algún valor dentro del *array*, por lo que la dimensión de este *array* es de 2. Es como acceder a un elemento en una lista de listas

    - *Número de elementos*: con el atributo `size` nos dice el número de elementos que  hay dentro del *array*, en este caso tenemos 10 números enteros

    - *Tipo de datos*: usando el atributo `dtype` conocemos que  el *array* esta compuesto por elementos de tipo *integer*. Recordad que en un *array* todos los elementos deben ser del mismo tipo. 


In [7]:
print("-------------ARRAY TRIDIMENSIONAL--------------")
print(f"El array tridimensional es: \n  {array_tridimensional}")
print(f"La forma del array tridimensional es: {array_tridimensional.shape}")
print(f"El número de dimensiones del array tridimensional es: {array_tridimensional.ndim}")
print(f"El número de elementos del array tridimensional es: {array_tridimensional.size}")
print(f"El tipo de dato que tenemos en el array tridimensional es: {array_tridimensional.dtype}\n")

-------------ARRAY TRIDIMENSIONAL--------------
El array tridimensional es: 
  [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
La forma del array tridimensional es: (2, 2, 5)
El número de dimensiones del array tridimensional es: 3
El número de elementos del array tridimensional es: 20
El tipo de dato que tenemos en el array tridimensional es: int32



Entendamos los resultados que hemos obtenido en la celda anterior: 

- ***array* tridimensional**

    - *Forma*: en este caso la tupla esta compuesta por tres valores. Esto lo podemos interpretar de la siguiente forma, tenemos 3 dimensiones, la primera hace referencia al número de *arrays* más pequeños que tenemos en nuestro *array* principal (en este caso 2, es decir, tenemos dos *arrays*). Luego tenemos dos valores más que son el 2 y el 5 que indican que cada uno de los *arrays* pequeños tienen dos filas y 5 columnas. 

    - *Número de dimensiones*: En este caso necesitamos tres índices para acceder a algún valor dentro del *array*, por lo que la dimensión de este *array* es de 3. 

    - *Número de elementos*: con el atributo `size` nos dice el número de elementos que  hay dentro del *array*, en este caso tenemos 20 números enteros

    - *Tipo de datos*: usando el atributo `dtype` conocemos que  el *array* esta compuesto por elementos de tipo *integer*. Recordad que en un *array* todos los elementos deben ser del mismo tipo. 


Comprendiendo las diferencias entre los distintos tipos de *arrays* y sus propiedades, sigamos viendo otras formas de crear **arrays**. 

## Crear un array vacío

Al igual que en el caso anterior, podremos crear *arrays* vacíos de distintas dimensiones. Su sintaxis básica es:


```python
np.empty(shape, dtype=float)
```
- `shape`: Especifica la forma (dimensiones) del *array* que se creará. Puede ser un entero, una tupla de enteros o una lista de enteros. 

- `dtype` (opcional): Especifica el tipo de datos de los elementos del *array*. Por defecto, es `float`, lo que significa que los elementos del *array* serán números de punto flotante. También se pueden especificar otros tipos de datos, como `int` para números enteros, `bool` para valores booleanos, `str` para cadenas de texto, entre otros.


Aquí tienes algunos ejemplos de cómo utilizar `np.empty`:

```python
import numpy as np

# Crear un array vacío de 2 filas y 3 columnas
array_vacio = np.empty((2, 3))
print(array_vacio)

# Crear un array vacío de forma (4, )
array_vacio_1D = np.empty(4)
print(array_vacio_1D)
```

El método `np.empty` crea un *array* vacío sin inicializar sus elementos. Esto significa que los valores de los elementos pueden ser impredecibles y dependerán de los datos almacenados previamente en la memoria.

In [8]:
print("------------- ARRAY UNIDIMENSIONAL VACÍO --------------")

# creamos el array vacío unidimensional especificando el número de elementos que queremos tener en el array. 
# como solo tiene una dimensión solo le paso un valor. Nos genera un array con 4 valores.
array_vacio_unidimensional =  np.empty(4)
print(f"El array unidimensional creado a partir del método np.emtpy(): \n  {array_vacio_unidimensional} \n")

------------- ARRAY UNIDIMENSIONAL VACÍO --------------
El array unidimensional creado a partir del método np.emtpy(): 
  [2.12199579e-314 1.03977794e-311 9.05128263e-321 6.95293141e-310] 



In [8]:
print("------------- ARRAY BIDIMENSIONAL VACÍO --------------")

# creamos el array vacío bidimensional especificando el número de elementos que queremos tener en el array. 
# como en este caso queremos tener dos dimensiones, le tendremos que pasar dos valores, con el número de elementos que queremos en cada una de ellas
# el primer valor hace referencia al número de filas y el segundo al número de columnas
array_vacio_bidimensional =  np.empty((4,2))
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_vacio_bidimensional} \n")


------------- ARRAY BIDIMENSIONAL VACÍO --------------
El array bidimensional creado a partir del método np.emtpy(): 
  [[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 9.66392403e-321]
 [8.45603440e-307 4.45046007e-307]] 



In [9]:
print("------------- ARRAY TRIDIMENSIONAL VACÍO --------------")

# creamos el array vacío tridimensional especificando el número de elementos que queremos tener en el array. 
# queremos tener tres dimensiones, por lo que le tendremos que pasar tres valores, con el número de elementos que queremos en cada una de ellas
# el primer valor hace referencia al número de arrays "pequeños" que queremos, el segundo al número de filas y el último al número de columnas
array_vacio_tridimensional =  np.empty((3, 4, 2)) # estamos generando un array de tres matrices donde cada una de ellas tienen 4 filas y 2 columnas
print(f"El array tridimensional creado a partir del método np.emtpy(): \n  {array_vacio_tridimensional} \n")

------------- ARRAY TRIDIMENSIONAL VACÍO --------------
El array tridimensional creado a partir del método np.emtpy(): 
  [[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.33511426e-306]
  [1.37961709e-306 7.56599807e-307]
  [8.90104239e-307 1.24610383e-306]]

 [[1.69118108e-306 8.06632139e-308]
  [1.20160711e-306 1.69119330e-306]
  [1.29062229e-306 1.60217812e-306]
  [1.37961370e-306 1.69118515e-306]]

 [[1.11258277e-307 1.05700515e-307]
  [1.11261774e-306 1.29060871e-306]
  [8.34424766e-308 8.34445138e-308]
  [1.37959129e-306 1.02360528e-306]]] 



## Crear un array de ceros

Permite crear un *array* compuesto solo por 0. La sintaxis del método `np.zeros` en NumPy es la siguiente:

```python
np.zeros(shape, dtype=float)
```

- `shape`: Especifica la forma (dimensiones) del *array* que se creará. Puede ser un entero, una tupla de enteros o una lista de enteros.

- `dtype` (opcional): Especifica el tipo de datos de los elementos del *array*. Por defecto, es `float`, lo que significa que los elementos del *array* serán números de punto flotante. También se pueden especificar otros tipos de datos, como `int` para números enteros, `bool` para valores booleanos, `str` para cadenas de texto, entre otros.



In [10]:
print("------------- ARRAY UNIDIMENSIONAL DE CEROS --------------")

# creamos el array unidimensional especificando el número de elementos que queremos tener en el array. 
# como solo tiene una dimensión solo le paso un valor.
array_vacio_unidimensional_cero =  np.zeros(4)
print(f"El array unidimensional creado a partir del método np.zeros(): \n  {array_vacio_unidimensional_cero} \n")

------------- ARRAY UNIDIMENSIONAL DE CEROS --------------
El array unidimensional creado a partir del método np.zeros(): 
  [0. 0. 0. 0.] 



In [12]:
print("------------- ARRAY BIDIMENSIONAL DE CEROS --------------")

# la lógica y la sintaxis va a ser la misma que cuando creabamos los arrays vacíos
# creamos un array de 0 con 4 filas y 2 columnas
array_vacio_bidimensional_cero =  np.zeros((4,2))
print(f"El array bidimensional creado a partir del método np.zeros(): \n  {array_vacio_bidimensional_cero} \n")

------------- ARRAY BIDIMENSIONAL DE CEROS --------------
El array bidimensional creado a partir del método np.zeros(): 
  [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 



In [13]:
print("------------- ARRAY TRIDIMENSIONAL DE CEROS --------------")

# estamos generando un array de 0 con 3 matrices donde cada una de ellas tienen 4 filas y 2 columnas
array_vacio_tridimensional_cero =  np.zeros((3, 4, 2)) 
print(f"El array tridimensional creado a partir del método np.zeros(): \n  {array_vacio_tridimensional_cero} \n")

------------- ARRAY TRIDIMENSIONAL DE CEROS --------------
El array tridimensional creado a partir del método np.zeros(): 
  [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]] 




## Crear un array de unos

Crea un *array* formado unicamente por 1. La sintaxis del método `np.ones` en NumPy es la siguiente:

```python
np.ones(shape, dtype=None)
```

- `shape`: Especifica la forma (dimensiones) del array que se creará. Puede ser un entero, una tupla de enteros o una lista de enteros. 


- `dtype` (opcional): Especifica el tipo de datos de los elementos del array. Por defecto, es `None`, lo que significa que los elementos del array serán números de punto flotante. También se pueden especificar otros tipos de datos, como `int` para números enteros, `bool` para valores booleanos, `str` para cadenas de texto, entre otros.

In [14]:
print("------------- ARRAY UNIDIMENSIONAL DE UNOS --------------")

# creamos el array unidimensional especificando el número de elementos que queremos tener en el array. 
# como solo tiene una dimensión solo le paso un valor.
array_vacio_unidimensional_unos =  np.ones(4)
print(f"El array unidimensional creado a partir del método np.ones(): \n  {array_vacio_unidimensional_unos} \n")

------------- ARRAY UNIDIMENSIONAL DE UNOS --------------
El array unidimensional creado a partir del método np.ones(): 
  [1. 1. 1. 1.] 



In [15]:
print("------------- ARRAY BIDIMENSIONAL DE UNOS --------------")

# estamos creando un array de dos dimensiones con 4 filas y 2 columnas
array_vacio_bidimensional_unos =  np.ones((4,2))
print(f"El array bidimensional creado a partir del método np.ones(): \n  {array_vacio_bidimensional_unos} \n")

------------- ARRAY BIDIMENSIONAL DE UNOS --------------
El array bidimensional creado a partir del método np.ones(): 
  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



In [16]:
print("------------- ARRAY TRIDIMENSIONAL DE UNOS --------------")

# creamos el array tridimensional especificando el número de elementos que queremos tener en el array. 
array_vacio_tridimensional_unos =  np.ones((3, 4, 2)) # estamos generando un array de tres matrices donde cada una de ellas tienen 4 filas y 2 columnas
print(f"El array tridimensional creado a partir del método np.ones(): \n  {array_vacio_tridimensional_unos} \n")

------------- ARRAY TRIDIMENSIONAL DE UNOS --------------
El array tridimensional creado a partir del método np.ones(): 
  [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]] 



## Crear un array con valores secuenciales


Funciona de forma similar al `range()` de Python, pero en este caso nos genera un *array*. La sintaxis del método `np.arange` en NumPy es la siguiente:

```python
np.arange(start, stop, step, dtype=None)
```

- `start` (opcional): Especifica el valor de inicio de la secuencia. Por defecto, es 0.

- `stop`: Especifica el valor final de la secuencia (exclusivo). Es decir, la secuencia generada no incluirá este valor.

- `step` (opcional): Especifica el incremento (salto) entre los valores de la secuencia. Por defecto, es 1.

- `dtype` (opcional): Especifica el tipo de datos de los elementos en el array. Por defecto, es `None`, lo que significa que se utilizará el tipo de datos predeterminado.


📌 Por defecto nos devuelve una matriz unidimensional. En caso de que queramos cambiar las dimensiones del *array* tendremos que aplicar el método `reshape` que veremos mas adelante. 

In [17]:
print("------------- ARRAY UNIDIMENSIONAL CON 4 ELEMENTOS --------------")

array_unidimensional_arange_1 =  np.arange(4)
print(f"El array unidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange_1} \n")


print("------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 4 (no incluido) CON SALTOS DE 1 EN 1  --------------")
array_unidimensional_arange_2 =  np.arange(1,4,1)
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange_2} \n")


print("------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 20 (no incluido) CON SALTOS DE 2 EN 2  --------------")
array_unidimensional_arange_3 =  np.arange(1,20,2)
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange_3} \n")


------------- ARRAY UNIDIMENSIONAL CON 4 ELEMENTOS --------------
El array unidimensional creado a partir del método np.emtpy(): 
  [0 1 2 3] 

------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 4 (no incluido) CON SALTOS DE 1 EN 1  --------------
El array bidimensional creado a partir del método np.emtpy(): 
  [1 2 3] 

------------- ARRAY UNIDIMENSIONAL CON NÚMEROS DEL 1 AL 20 (no incluido) CON SALTOS DE 2 EN 2  --------------
El array bidimensional creado a partir del método np.emtpy(): 
  [ 1  3  5  7  9 11 13 15 17 19] 



## Crear un array usando random

El módulo `random` de NumPy proporciona funciones para generar números aleatorios con diferentes distribuciones y características. Estas funciones son útiles para simular datos aleatorios y realizar experimentos numéricos. Algunos de los métodos más utilizados del módulo `random` de NumPy:


1. `np.random.randint`: Genera números enteros aleatorios en un array. Puedes especificar el rango de los números enteros y la forma del array como argumentos.

2. `np.random.rand`: Genera números aleatorios en un *array* en el rango [0, 1).  Es decir, los números generados estarán en el intervalo semiabierto [0, 1), donde 0 está incluido y 1 está excluido.

3. `np.random.sample`: Genera números aleatorios en un *array*  en el rango [0, 1).


### np.random.randint

La sintaxis básica del método `np.random.randint` es la siguiente:

```python
numpy.random.randint(low, high, size, dtype)
```

Donde:

- `low`: Especifica el límite inferior del rango de números enteros a generar (inclusive). Si solo se proporciona este argumento, los números aleatorios se generarán en el rango [0, low). Es decir, el límite superior no está incluido en el rango.

- `high` (opcional): Especifica el límite superior del rango de números enteros a generar (exclusivo). Si se proporciona este argumento, los números aleatorios se generarán en el rango [low, high). 

- `size` (opcional): Especifica la forma del *array* resultante de números enteros aleatorios. Puede ser un número entero o una tupla de enteros que represente las dimensiones del *array*. Por defecto, es `None`, lo que implica que se generará un solo número entero,  es decir, un array unidimensional.

- `dtype` (opcional): Especifica el tipo de dato de los elementos en el *array*. Por defecto, es `int`, lo que significa que los números enteros se generarán como enteros estándar.



In [23]:
print("------------- ARRAY UNIDIMENSIONAL RANDINT --------------")
# en este caso estamos generando un array unidimensional con un valor aleatorio que puede variar entre 0 y 9 (no incluido)
array_randint_uni = np.random.randint(9)
print(f"El array unidimensional creado a partir del método np.random.randint(): \n  {array_randint_uni} \n")

------------- ARRAY UNIDIMENSIONAL RANDINT --------------
El array unidimensional creado a partir del método np.random.randint(): 
  6 



In [25]:
print("------------- ARRAY BIDIMENSIONAL RANDINT --------------")
# generamos un array bidimensional con números aleatorios entre el 0 y el 50 (no incluido) de 2 filas y 3 columnas
array_randint_bi = np.random.randint(0, 50, (2,3))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi} \n")

------------- ARRAY BIDIMENSIONAL RANDINT --------------
El array bidimensional creado a partir del método np.random.randint(): 
  [[13 21 42]
 [ 6 39 12]] 



In [26]:
print("------------- ARRAY TRIDIMENSIONAL RANDINT --------------")
# generamos un array tridimensional de números aleatorios entre el 0 y 20 (no incluido) de 2 matrices, 3 filas y 4 columnas
array_randint_tri = np.random.randint(0, 20, (2, 3, 4))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_tri} \n")

------------- ARRAY TRIDIMENSIONAL RANDINT --------------
El array bidimensional creado a partir del método np.random.randint(): 
  [[[ 4  2  7  8]
  [ 7 12 12 16]
  [16 12 16 19]]

 [[ 5  9 10 18]
  [16 14 14 18]
  [ 0  3 17 19]]] 



### np.random.rand

La sintaxis básica del método `np.random.rand` es la siguiente:

```python
numpy.random.rand(d0, d1, ..., dn)
```

- `d0, d1, ..., dn` son los argumentos opcionales que determinan las dimensiones de la matriz de números aleatorios que se generará. Puedes proporcionar cualquier número de argumentos, lo que significa que puedes crear matrices unidimensionales, bidimensionales, tridimensionales, etc.

📝 **NOTA**: en este caso no tenemos que especificar que entre que valores queremos que nos genere los números. POR DEFECTO NOS GENERARÁ NÚMEROS ALEATORIOS ENTRE EL 0-1.

📝 **NOTA**: Solo nos dará *floats*, por lo que no hace falta especificar el tipo. 

In [29]:
print("------------- ARRAY UNIDIMENSIONAL RAND --------------")
# en este caso estamos generando un array unidimensional con cuatro valores aleatorios entre el 0 y el 1

array_rand_uni = np.random.rand(4)
print(f"El array unidimensional creado a partir del método np.random.rand(): \n  {array_rand_uni} \n")

------------- ARRAY UNIDIMENSIONAL RAND --------------
El array unidimensional creado a partir del método np.random.rand(): 
  [0.12927328 0.64603016 0.62100281 0.80749648] 



In [30]:
print("------------- ARRAY BIDIMENSIONAL RAND --------------")
# en este caso estamos generando un array bidimensional de 2 filas y 3 columnas con números aleatorios entre el 0 y el 1

array_rand_bi = np.random.rand(2,3)
print(f"El array unidimensional creado a paratir del método np.random.rand(): \n  {array_rand_bi} \n")


------------- ARRAY BIDIMENSIONAL RAND --------------
El array unidimensional creado a paratir del método np.random.rand(): 
  [[0.09224886 0.61650856 0.33309738]
 [0.00436105 0.01863938 0.36121589]] 



In [31]:
print("------------- ARRAY TRIDIMENSIONAL RAND --------------")
# en este caso estamos generando un array tridimensional de 2 matrices, 3 filas  y 4 columnas con números aleatorios entre el 0 y el 1

array_rand_tri = np.random.rand(2,3,4)
print(f"El array unidimensional creado a partir del método np.random.rand(): \n  {array_rand_tri} \n")


------------- ARRAY TRIDIMENSIONAL RAND --------------
El array unidimensional creado a partir del método np.random.rand(): 
  [[[0.51115945 0.98237061 0.04587228 0.55518975]
  [0.17544096 0.84995362 0.1126362  0.93032473]
  [0.8744532  0.66341478 0.40724235 0.74889965]]

 [[0.39829889 0.24715784 0.28550643 0.26378724]
  [0.04076521 0.73200015 0.59643603 0.46574509]
  [0.13161445 0.5633391  0.71780566 0.29721443]]] 



### np.random.random_sample

La sintaxis básica del método `np.random.random_sample` es la siguiente:

```python
numpy.random.random_sample(size=None)
```

Donde:

- `size` (opcional): Permite especificar la forma del array resultante. Puede ser un número entero o una tupla de enteros que represente las dimensiones del array. Si no se proporciona el parámetro `size`, se devuelve un solo número aleatorio en el rango [0, 1).

In [28]:
print("------------- ARRAY UNIDIMENSIONAL RANDOM_SAMPLE --------------")
# en este caso estamos generando un array unidimensional con 4 valores aleatorios entre el 0 y el 1
array_sample_uni = np.random.random_sample(4)
print(f"El array unidimensional creado a partir del método np.random.random_sample(): \n  {array_sample_uni} \n")

------------- ARRAY UNIDIMENSIONAL RANDOM_SAMPLE --------------
El array unidimensional creado a partir del método np.random.random_sample(): 
  [0.21032398 0.28211361 0.46158271 0.03498543] 



In [29]:
print("------------- ARRAY BIDIMENSIONAL RANDOM_SAMPLE --------------")
# en este caso estamos generando un array bidimensional de 2 filas y 3 columnas con números aleatorios entre el 0 y el 1

array_sample_bi = np.random.random_sample((2,3))
print(f"El array unidimensional creado a paratir del método np.random.random_sample(): \n  {array_sample_bi} \n")

------------- ARRAY BIDIMENSIONAL RANDOM_SAMPLE --------------
El array unidimensional creado a paratir del método np.random.random_sample(): 
  [[0.63858968 0.6475517  0.87604607]
 [0.86397408 0.28783955 0.05633572]] 



In [30]:
print("------------- ARRAY TRIDIMENSIONAL RANDOM_SAMPLE --------------")
# en este caso estamos generando un array tridimensional de 2 matrices, 3 filas  y 4 columnas con números aleatorios entre el 0 y el 1

array_sample_tri = np.random.random_sample((2,3, 4))
print(f"El array unidimensional creado a partir del método  np.random.random_sample(): \n  {array_sample_tri} \n")


------------- ARRAY TRIDIMENSIONAL RANDOM_SAMPLE --------------
El array unidimensional creado a partir del método  np.random.random_sample(): 
  [[[0.90568966 0.12205224 0.66750121 0.27144243]
  [0.44671676 0.89712666 0.89168801 0.45469966]
  [0.54192768 0.69760742 0.9234935  0.85228903]]

 [[0.05770072 0.49866865 0.54917379 0.94973572]
  [0.34227515 0.38030377 0.03047187 0.41339593]
  [0.1405848  0.05548365 0.53298574 0.34816309]]] 

