In [2]:
! pip install numpy

In [1]:
# Importación de librerías
import numpy as np

In [7]:
# Generamos un array unidimensional de 5 elementos, de ejemplo:
np.array_1d = [1, 2, 3, 4, 5]

 AND &
 
  OR |


In [ ]:
# Por defecto, los arrays son tipo float. Para convertirlos a integer:
int(np.mean(array_2d))

In [2]:
# 1. Genera un array bidimensional de 4 filas x 3 columnas con valores aleatorios 
# enteros entre el 34 y el 98. Una vez creado cada array comprueba 
# las dimensiones y los tipos de datos que tenemos en el array.

array_aleatorio = np.random.randint(34, 99, size=(4,3))

In [4]:
array_aleatorio

array([[39, 88, 39],
       [85, 77, 57],
       [84, 64, 57],
       [51, 44, 37]])

In [7]:
# Comprobamos las dimensiones del array:
dimensiones = array_aleatorio.shape

In [8]:
# Comprobamos el tipo de dato que tengo en el array
tipo_dato = array_aleatorio.dtype

In [9]:
# Imprimir el array generado, dimensiones y tipo de dato
print("Array generado:")
print(array_aleatorio)
print("Dimensiones del array:", dimensiones)
print("Tipo de dato del array:", tipo_dato)

Array generado:
[[39 88 39]
 [85 77 57]
 [84 64 57]
 [51 44 37]]
Dimensiones del array: (4, 3)
Tipo de dato del array: int32


In [12]:
# 2. Crea dos arrays (unidimensional, bidimensional) usando el método 
# np.array().
# Las listas para crear los arrays son las siguientes

lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

array_unidimensional = np.array(lista1)

array_bidimensional = np.array(lista2)

In [13]:
print("descripcion del array unidimensional")
print("-----------------------------------------")
print(f"El array unidimensional es: \n  {array_unidimensional}")
print(f"La forma del array unidimensional es: {array_unidimensional.shape}")
print(f"El número de dimensiones del array unidimensional es: {array_unidimensional.ndim}")
print(f"El número de elementos del array unidimensional es: {array_unidimensional.size}")
print(f"El tipo de dato que tenemos en el array unidimensional es: {array_unidimensional.dtype}\n")
print()
print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")
print()
print("descripcion del array bidimensional")
print("-----------------------------------------")
print(f"El array bidimensional es: \n  {array_bidimensional}")
print(f"La forma del array bidimensional es: {array_bidimensional.shape}")
print(f"El número de dimensiones del array bidimensional es: {array_bidimensional.ndim}")
print(f"El número de elementos del array bidimensional es: {array_bidimensional.size}")
print(f"El tipo de dato que tenemos en el array bidimensional es: {array_bidimensional.dtype}\n")

descripcion del array unidimensional
-----------------------------------------
El array unidimensional es: 
  [34 56 71 98 10]
La forma del array unidimensional es: (5,)
El número de dimensiones del array unidimensional es: 1
El número de elementos del array unidimensional es: 5
El tipo de dato que tenemos en el array unidimensional es: int32


-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

descripcion del array bidimensional
-----------------------------------------
El array bidimensional es: 
  [[23 45 89 56]
 [12 43 82 44]]
La forma del array bidimensional es: (2, 4)
El número de dimensiones del array bidimensional es: 2
El número de elementos del array bidimensional es: 8
El tipo de dato que tenemos en el array bidimensional es: int32



In [20]:
# 3. Crea un array unidimensional con 50 elementos con el método que 
# prefieras y extrae:

array3= np.random.randint(34, 98, (1, 50))

# El primer elemento.
print("El primer elemento del array es:", array3[0][0])
# Lo elementos que están en posición impar.
print("Los elementos de posición impar son:", array3[0][1::2])
# Los cuatro primeros elementos.
print("Los 4 primeros elementos son:", array3[0][:5])
# Los últimos tres elementos.
print("Los últimos 3 elementos son:", array3[0][-3:])
# Los elementos entre el 4 y el 8 (incluido).
print("Los elementos entre el 4 y el 8 incluido son:", array3[0][4:9])

El primer elemento del array es: 70
Los elementos de posición impar son: [76 42 77 96 66 52 47 78 84 90 86 84 91 96 96 82 66 39 89 55 35 76 51 79
 89]
Los 4 primeros elementos son: [70 76 50 42 66]
Los últimos 3 elementos son: [79 89 89]
Los elementos entre el 4 y el 8 incluido son: [66 77 89 96 81]


In [22]:
# 4. Crea un array de dos dimensiones de 4 x 5 con el método que 
# prefieras y extrae:

array4 = np.random.randint(0,99, (4,5))

print(array4)

# La primera fila y todas las columnas.
print("La primera fila y todas las columnas son:", array4[0, :])

# Todas las filas pares.
print("Las filas pares son:", array4[0::2])

# La primera columna y todas las filas.
print("La primera columna y todas las filas:", array4[:, 0])

[[40 88 59 13 33]
 [ 5 43 47 42 51]
 [75 41 65 11 77]
 [65 82 48 52 94]]
La primera fila y todas las columnas son: [40 88 59 13 33]
Las filas pares son: [[40 88 59 13 33]
 [75 41 65 11 77]]
La primera columna y todas las filas: [40  5 75 65]


In [68]:
# 5. Crea un array bidimensional con 20 elementos aleatrorios entre
#  0 y 50 con el método que prefieras y:
# Crea una mascara o filtro donde los valores mayores a 30 y 
# menores a 10 se reemplace por "objetivo" y el resto por 
# "no es mi objetivo".
# Los valores de mi array bidimensional multiplicalos por el
#  escalar 10.

array5 = np.random.randint(0, 50, (2,10))

In [74]:
array5

array([[18, 25, 48, 35, 46, 43, 20, 46, 23, 14],
       [ 9, 20,  1, 21, 27, 26, 44, 40, 49, 18]])

In [72]:
# Crea una mascara o filtro donde los valores mayores a 30 y 
# menores a 10 se reemplace por "objetivo" y el resto por 
# "no es mi objetivo".

mascara = (array5 > 10) & (array5 < 30)
array_condicion = np.where(mascara, "objetivo","no es mi objetivo")

In [73]:
array_condicion

array([['objetivo', 'objetivo', 'no es mi objetivo', 'no es mi objetivo',
        'no es mi objetivo', 'no es mi objetivo', 'objetivo',
        'no es mi objetivo', 'objetivo', 'objetivo'],
       ['no es mi objetivo', 'objetivo', 'no es mi objetivo', 'objetivo',
        'objetivo', 'objetivo', 'no es mi objetivo', 'no es mi objetivo',
        'no es mi objetivo', 'objetivo']], dtype='<U17')

In [69]:
array5

array([[18, 25, 48, 35, 46, 43, 20, 46, 23, 14],
       [ 9, 20,  1, 21, 27, 26, 44, 40, 49, 18]])

In [75]:
# Los valores de mi array bidimensional multiplicalos por el escalar 10.

array5 * 10

array([[180, 250, 480, 350, 460, 430, 200, 460, 230, 140],
       [ 90, 200,  10, 210, 270, 260, 440, 400, 490, 180]])

In [80]:
# 6. Crea un nuevo array de dos dimensiones con la misma forma que 
# el anterior y 
# con el método que prefieras y realiza lo siguiente:

array6 = np.random.randint(0,50,(2,10))
array61 = np.random.randint(0,50,(2,10))

In [83]:
array6 

array([[ 9, 17, 38, 42, 16, 22, 36, 47,  3, 31],
       [13,  4, 35, 31, 45, 14, 37, 34, 25, 30]])

In [82]:
array61


array([[11,  9, 42, 14, 43, 45, 14, 31, 34, 16],
       [14, 48,  6, 37, 49,  8, 27, 31, 11,  8]])

In [84]:
# Suma el primer array con el segundo.
array6 + array61

array([[20, 26, 80, 56, 59, 67, 50, 78, 37, 47],
       [27, 52, 41, 68, 94, 22, 64, 65, 36, 38]])

In [85]:
# Aplicar la potencia para el primer array elevado al segundo.

array6 ** array61

array([[ 1316288537, -1671207791,           0,  1003634688,           0,
                  0,   268435456,    69729487,  -217042295,  1353309697],
       [ -523170343,           0,  1838265625,  1632803999,   635433965,
         1475789056, -2134678531, -2147483648, -2094601527, -1029996288]])

In [86]:
# 7. Crea un array, puede ser bidimensional! Eso si, los valores tienen 
# que estar entre 0-100. calcula:

array7 = np.random.randint(0,100,(2,10))

# La media de los elementos
np.mean(array7)
# La media de las columnas y redondéalo a dos decimales
mean = np.mean(array7, axis = 0)
np.round(mean,2)
# El valor máximo de cada fila
np.max(array7, axis = 0)
# El valor mínimo de cada fila
np.min(array7, axis = 0)
# Hay algun valor que sea mayor que 90 en tu array
array7 [ array7 > 90]
# Donde los podemos encontrar, cuáles son sus índices
np.argwhere(array7 > 70)
# Ordena el array de mayor a menor
array_ordenado = np.sort(array7)

In [88]:
array7 

array([[85, 53, 23, 39, 13, 43, 36, 70, 73, 12],
       [67, 69, 10, 77, 81, 28, 80, 32, 22, 60]])

In [95]:
mean = np.mean(array7, axis = 0)


In [102]:
np.round(mean,2)

array([76. , 61. , 16.5, 58. , 47. , 35.5, 58. , 51. , 47.5, 36. ])

In [105]:
np.max(array7, axis = 0)

array([85, 69, 23, 77, 81, 43, 80, 70, 73, 60])

In [106]:
np.min(array7, axis = 0)

array([67, 53, 10, 39, 13, 28, 36, 32, 22, 12])

In [113]:
# cogemos 70 porque no hay mayores que 90

array7 [ array7 > 70]

array([85, 73, 77, 81, 80])

In [116]:
array7

array([[85, 53, 23, 39, 13, 43, 36, 70, 73, 12],
       [67, 69, 10, 77, 81, 28, 80, 32, 22, 60]])

In [117]:
np.argwhere(array7 > 70)

array([[0, 0],
       [0, 8],
       [1, 3],
       [1, 4],
       [1, 6]], dtype=int64)

In [118]:
array_ordenado = np.sort(array7)

In [119]:
array_ordenado

array([[12, 13, 23, 36, 39, 43, 53, 70, 73, 85],
       [10, 22, 28, 32, 60, 67, 69, 77, 80, 81]])